### PR TITLE
Fix issue 2102 (bug introduced in 2098)

### LINKED ISSUE #2102: Admin Error 500: 'MailuSessionConfig' object has no attribute 'app'
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
master

## Description
Admin and Webmail show 500 Internal Server Error.

The login page can be restored by deleting cookies, but nothing beyond the login page works.

## Replication Steps
Access `/admin` (and log in)

## Expected behaviour
Works normally.

## Logs

```
mailu-admin-1      | [2021-12-22 16:16:26,927] ERROR in app: Exception on /admin [GET]
mailu-admin-1      | Traceback (most recent call last):
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2072, in wsgi_app
mailu-admin-1      |     ctx.push()
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/ctx.py", line 404, in push
mailu-admin-1      |     self.session = session_interface.open_session(self.app, self.request)
mailu-admin-1      |   File "/app/mailu/utils.py", line 379, in open_session
mailu-admin-1      |     return MailuSession(request.cookies.get(app.config['SESSION_COOKIE_NAME'], None), app)
mailu-admin-1      |   File "/app/mailu/utils.py", line 195, in __init__
mailu-admin-1      |     if parsed := self.app.session_config.parse_key(key, self.app):
mailu-admin-1      |   File "/app/mailu/utils.py", line 360, in parse_key
mailu-admin-1      |     if not created <= now <= created + self.app.config['PERMANENT_SESSION_LIFETIME']:
mailu-admin-1      | AttributeError: 'MailuSessionConfig' object has no attribute 'app'
mailu-admin-1      | [2021-12-22 16:16:26,927] ERROR in app: Request finalizing failed with an error while handling an error
mailu-admin-1      | Traceback (most recent call last):
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2072, in wsgi_app
mailu-admin-1      |     ctx.push()
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/ctx.py", line 404, in push
mailu-admin-1      |     self.session = session_interface.open_session(self.app, self.request)
mailu-admin-1      |   File "/app/mailu/utils.py", line 379, in open_session
mailu-admin-1      |     return MailuSession(request.cookies.get(app.config['SESSION_COOKIE_NAME'], None), app)
mailu-admin-1      |   File "/app/mailu/utils.py", line 195, in __init__
mailu-admin-1      |     if parsed := self.app.session_config.parse_key(key, self.app):
mailu-admin-1      |   File "/app/mailu/utils.py", line 360, in parse_key
mailu-admin-1      |     if not created <= now <= created + self.app.config['PERMANENT_SESSION_LIFETIME']:
mailu-admin-1      | AttributeError: 'MailuSessionConfig' object has no attribute 'app'
mailu-admin-1      | 
mailu-admin-1      | During handling of the above exception, another exception occurred:
mailu-admin-1      | 
mailu-admin-1      | Traceback (most recent call last):
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1540, in finalize_request
mailu-admin-1      |     response = self.process_response(response)
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1885, in process_response
mailu-admin-1      |     response = self.ensure_sync(func)(response)
mailu-admin-1      |   File "/usr/lib/python3.9/site-packages/flask_login/login_manager.py", line 399, in _update_remember_cookie
mailu-admin-1      |     if '_remember' not in session and \
mailu-admin-1      | TypeError: argument of type 'NoneType' is not iterable
```

### PR DESCRIPTION
**Pull request by Diman0**
## What type of PR?

Bug-fix

## What does this PR do?
The changes to session management introduced in #2094 #2098 introduced new bugs. This PR addresses these.

### Related issue(s)
- Auto close an issue like: closes #2102

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

### CODE REVIEW

**Review by ghostwheel42 — APPROVED** [review]
Lgtm
